version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: |
                    sudo chmod +x gradlew 
                    ./gradlew build
      - run:
          name: Run UnitTest
          command: ./gradlew test
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-29;default;x86
          install: true
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          restore-gradle-cache-prefix: v1a
      - run:
          name: Run Instrumenation Tests
          command: ./gradlew connectedAndroidTest

