version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: |
                    sudo chmod +x gradlew 
                    ./gradlew build
      - run:
          name: Run UnitTest
          command: ./gradlew test
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
                  # wait for it to have booted
                  circle-android wait-for-boot
                  # unlock the emulator screen
                  sleep 30
                  adb shell input keyevent 82
      - run:
          name: Run Instrumenation Tests
          command: ./gradlew connectedAndroidTest
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest

