version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: |
                    sudo chmod +x gradlew 
                    ./gradlew build
      - run:
          name: Run UnitTest
          command: ./gradlew test